global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: go-backend-kit
    honor_timestamps: true
    track_timestamps_staleness: false
    scrape_interval: 10s
    scrape_timeout: 10s
    scrape_protocols:
    - OpenMetricsText1.0.0
    - OpenMetricsText0.0.1
    - PrometheusText1.0.0
    - PrometheusText0.0.4
    always_scrape_classic_histograms: false
    convert_classic_histograms_to_nhcb: false
    metrics_path: /metrics
    scheme: http
    enable_compression: true
    metric_name_validation_scheme: utf8
    metric_name_escaping_scheme: allow-utf-8
    follow_redirects: true
    enable_http2: true
    static_configs:
    - targets:
      - localhost:9091

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']
    metrics_path: '/metrics'