# Crawler Hub Configuration

[server]
# gRPC server address
grpc_addr = ":50051"
# HTTP API server address (for management)
http_addr = ":8080"

[redis]
# Redis connection settings
addr = "localhost:6379"
password = ""
db = 0
# Key prefix for all crawler-related keys
prefix = "crawler"

[cluster]
# Cluster identification
cluster_id = "crawler-cluster-1"
# Maximum nodes in cluster
max_nodes = 100

[coordinator]
# Task coordination settings
max_retries = 3
task_timeout = "5m"
reassign_interval = "30s"
batch_size = 10

[dispatcher]
# Task dispatching settings
queue_size = 10000
dispatch_interval = "1s"
max_tasks_per_node = 100

[communication]
# Node communication settings
heartbeat_interval = "5s"
heartbeat_timeout = "30s"
max_message_size = 10485760  # 10MB

[monitoring]
# Prometheus metrics
metrics_enabled = true
metrics_port = ":9090"

[logging]
# Logging configuration
level = "info"  # debug, info, warn, error
format = "json"  # json or text
output = "stdout"  # stdout, stderr, or file path